[build]
builder = "nixpacks"

[deploy]
startCommand = "npm install && npm run build && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
NODE_VERSION = "20"