services:
  - type: web
    name: ecommerce-admin
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SERVER_PORT
        value: 10000